language: python
sudo: false

env:
- TOXENV=py27
- TOXENV=py36

install:
- pip install virtualenv tox docutils coveralls

script:
- python setup.py test
- python setup.py check -r

after_success:
- coveralls
