language: python
sudo: false
python:
- 2.7
- 3.5
- 3.6

env:
  - TOXENV=py27
  - TOXENV=py35
  - TOXENV=py36

matrix:
  include:
  - python: "2.7"
    env: TOXENV=py27
  - python: "3.5"
    env: TOXENV=py35
  - python: "3.6"
    env: TOXENV=py36

install:
- pip install virtualenv tox docutils coveralls

script:
- python setup.py test
- python setup.py check -r

after_success:
- coveralls
